export enum ContainerPlatform {
  DOCKER = "DOCKER",
  DOCKER_COMPOSE = "DOCKER_COMPOSE",
  AZURE_CONTAINER_APPS = "AZURE_CONTAINER_APPS",
  AZURE_KUBERNETES_SERVICE = "AZURE_KUBERNETES_SERVICE",
  KUBERNETES = "KUBERNETES"
}
