export enum WorkUnit {
  INIT_BODY = "INIT_BODY",
  UNDERSTAND_REPO = "UNDERSTAND_REPO",
  SCAN_DIRECTORY = "SCAN_DIRECTORY",
  SCAN_FILE = "SCAN_FILE",
  CLASSIFY_FILE = "CLASSIFY_FILE",
  DETECT_STRUCTURE = "DETECT_STRUCTURE",
  DETECT_SMELLS = "DETECT_SMELLS",
  DETECT_NOISE = "DETECT_NOISE",
  MAP_PATTERN_TO_STACK = "MAP_PATTERN_TO_STACK",
  MAP_PATTERN_TO_REPOSITORY = "MAP_PATTERN_TO_REPOSITORY",
  APPLY_PATTERN = "APPLY_PATTERN",
  AVOID_ANTI_PATTERN = "AVOID_ANTI_PATTERN",
  UPDATE_BRAIN = "UPDATE_BRAIN",
  WRITE_ORGAN = "WRITE_ORGAN"
}
